name: zPvP
main: zPvP.Main
version: 0.0.1
author: NewWoldPlay
commands:
  pvp:
  specialist:
  urgal:
  kangaroo:
  archer:
  poseidon:
  ninja:
  ghoul:
  warps:
  chat:
  staffchat:
  Invsee:
  report:
  admin:
  main:
  setfps:
  setmain:
  setrdm:
  chat:
  limparchat:
  chat:
  